name: WorldJoin
description: A plugin to run commands and send messages on world join
version: 1.1.3
main: me.aBooDyy.WorldJoin.WorldJoin
softdepend: [PlaceholderAPI]
author: aBooDyy
website: aBooDyy.net

commands:
  worldjoin:
    description: plugin info.
    aliases: [wjoin]

permissions:
  worldjoin.admin:
    default: op
    description: gives you access to WorldJoin commands.
