name: WorldJoin
description: A plugin to run commands and send messages on world join
version: ${project.version}
main: net.aboodyy.worldjoin.WorldJoin
softdepend: [PlaceholderAPI]
author: aBooDyy
website: aBooDyy.net

permissions:
  worldjoin.admin:
    default: op
    description: Gives you access to all WorldJoin commands.
    children:
      worldjoin.help: true
      worldjoin.reload: true
      worldjoin.special.list: true
      worldjoin.special.add: true
      worldjoin.special.remove: true
      worldjoin.special.clear: true
  worldjoin.help:
    default: op
    description: Gives acces to the help command.
  worldjoin.reload:
    default: op
    description: Gives acces to the reload command.
  worldjoin.special.list:
    default: op
    description: Gives acces to the special list command.
  worldjoin.special.add:
    default: op
    description: Gives acces to the special add command.
  worldjoin.special.remove:
    default: op
    description: Gives acces to the special remove command.
  worldjoin.special.clear:
    default: op
    description: Gives acces to the special clear command.